version: '3'

services:
  db:
    container_name: flask_postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
        - ./backend/.env
    ports:
        - "5432:5432"
    volumes:
        - pg_flask2:/var/lib/postgresql/data

  flask:
    build: ./backend
    container_name: flask_backend
    env_file:
        - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  react:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
        - ./frontend/:/app

volumes:
  pg_flask2: